name: 'bss action'
description: 'bss action - study project'
inputs:
  repo-name:  # id of input
    description: 'repo name'
    required: true
    default: ${{ github.repository }}
  github_token: 
    description: 'github token'
    required: true
    default: ${{ github.token }}
  bs_token: 
    description: 'blindspot token, use GitHub Secret key -BS_TOKEN'
    required: true

outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: check-circle
  color: blue