name: 'bss action'
description: 'bss action - study project'
inputs:
  repo-name:  # id of input
    description: 'repo name'
    required: true
    default: 'repo'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: check-circle
  color: blue